Add and update the installation steps and files.
dracula/visual-studio pull request #22
Opened 2022-07-07 18:36 UTC by luxonauta

- :memo: Update the installation steps.
- :art: Updates the screenshot based on the new theme version.
- :package: Added the theme installation file for Visual Studio 2022 - this file is created using the [Theme Converter for Visual Studio](https://github.com/microsoft/theme-converter-for-vs) tool.

2022-07-09 16:39 UTC, zenorocha requested changes
The screenshot also needs to be updated - having a background with any color could become an issue when we update the website colors.

2022-07-09 16:39 UTC, zenorocha commented on INSTALL.md
> -### [Visual Studio](https://www.visualstudio.com/)
This title is important and can't be removed, without that it will not render the website correctly.

2022-07-09 16:39 UTC, zenorocha commented on INSTALL.md
> +### Downloading using Git
This should be a an H4 (`####`)

2022-07-09 16:39 UTC, zenorocha commented on INSTALL.md
> +### Downloading manually
Same here

2022-07-09 16:39 UTC, zenorocha commented on INSTALL.md
> +If you have questions about Visual Studio, the best place to look for help is on the [official Visual Studio product family documentation](https://docs.microsoft.com/en-gb/visualstudio/).
This whole section isn't needed and also doesn't follow the standard of other repos.

2022-07-09 17:53 UTC, zenorocha commented
I noticed that the theme name on Visual Studio is `draculatheme`, can we change to `Dracula Theme`

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/398893/178117318-85ff2ec1-4abd-4334-8ae5-9aad3088b531.png">

2022-07-09 21:27 UTC, zenorocha commented
Should the [dracula.vssettings](https://github.com/dracula/visual-studio/blob/master/dracula.vssettings) file be removed?

2022-07-18 13:36 UTC, luxonauta commented
> Should the [dracula.vssettings](https://github.com/dracula/visual-studio/blob/master/dracula.vssettings) file be removed?

Zeno, I thought about removing it, but as I don't know if this method works on Mac OS, I left the file thinking about compatibility; for that reason, I just left the steps for installing on Mac OS the same.

2022-07-18 14:03 UTC, luxonauta commented
> I noticed that the theme name on Visual Studio is `draculatheme`, can we change to `Dracula Theme`
> 
> <img alt="image" width="1552" src="https://user-images.githubusercontent.com/398893/178117318-85ff2ec1-4abd-4334-8ae5-9aad3088b531.png">

:pencil2::white_check_mark: Fixed Zeno:

![image](https://user-images.githubusercontent.com/48334856/179528460-55770d44-711d-4558-b9ef-df119ad32e35.png)

2022-08-19 22:40 UTC, zenorocha approved these changes

2022-08-19 22:40 UTC, merged